"""add kyc_records table in kyc schema

Revision ID: 098aa29084a2
Revises: 47774a372ee4
Create Date: 2026-06-27 13:51:01.809688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098aa29084a2'
down_revision: Union[str, Sequence[str], None] = '47774a372ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_pii', sa.LargeBinary(), nullable=False),
    sa.Column('wrapped_dek', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_iv', sa.LargeBinary(), nullable=False),
    sa.Column('auth_tag', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='kyc'
    )
    op.create_index('idx_kyc_records_user_id', 'kyc_records', ['user_id'], unique=False, schema='kyc')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_kyc_records_user_id', table_name='kyc_records', schema='kyc')
    op.drop_table('kyc_records', schema='kyc')
    # ### end Alembic commands ###
