"""add idempotency columns to transactions table

Revision ID: 2ca894c97a9c
Revises: 098aa29084a2
Create Date: 2026-06-27 13:57:57.879561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca894c97a9c'
down_revision: Union[str, Sequence[str], None] = '098aa29084a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('request_hash', sa.String(length=64), nullable=True), schema='ledger')
    op.add_column('transactions', sa.Column('response_payload', sa.Text(), nullable=True), schema='ledger')
    op.add_column('transactions', sa.Column('response_status', sa.Integer(), nullable=True), schema='ledger')
    op.create_index('idx_transactions_user_idemp', 'transactions', ['user_id', 'idempotency_key'], unique=True, schema='ledger')
    # ### end Alembic commands ###
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute("REVOKE UPDATE, DELETE, TRUNCATE, REFERENCES ON ledger.account_ledger FROM PUBLIC;")


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute("GRANT UPDATE, DELETE, TRUNCATE, REFERENCES ON ledger.account_ledger TO PUBLIC;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transactions_user_idemp', table_name='transactions', schema='ledger')
    op.drop_column('transactions', 'response_status', schema='ledger')
    op.drop_column('transactions', 'response_payload', schema='ledger')
    op.drop_column('transactions', 'request_hash', schema='ledger')
    # ### end Alembic commands ###
