"""alloydb unified baseline

Revision ID: 2ea57c78ba89
Revises: 
Create Date: 2026-07-16 12:12:19.993754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import utils.database


# revision identifiers, used by Alembic.
revision: str = '2ea57c78ba89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    schema='admin'
    )
    op.create_index(op.f('ix_admin_system_settings_key'), 'system_settings', ['key'], unique=False, schema='admin')
    op.create_table('audit_outbox',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    schema='audit'
    )
    op.create_index('idx_audit_outbox_created_at', 'audit_outbox', ['created_at'], unique=False, schema='audit')
    op.create_index('idx_audit_outbox_event_type', 'audit_outbox', ['event_type'], unique=False, schema='audit')
    op.create_table('credit_products',
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('min_credit_limit_cents', sa.BigInteger(), nullable=False),
    sa.Column('max_credit_limit_cents', sa.BigInteger(), nullable=False),
    sa.Column('purchase_apr', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('cashback_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('travel_multiplier', sa.Integer(), nullable=False),
    sa.Column('dining_multiplier', sa.Integer(), nullable=False),
    sa.Column('annual_fee_cents', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('product_code'),
    schema='catalog'
    )
    op.create_table('deposit_products',
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('annual_percentage_yield', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('monthly_maintenance_fee_cents', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('product_code'),
    schema='catalog'
    )
    op.create_table('users',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('auth_provider_uid', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_users_auth_provider_uid'), 'users', ['auth_provider_uid'], unique=True, schema='identity')
    op.create_index(op.f('ix_identity_users_email'), 'users', ['email'], unique=False, schema='identity')
    op.create_table('merchant_category_codes',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('mcc', sa.String(length=10), nullable=False),
    sa.Column('primary_category', sa.String(length=50), nullable=False),
    sa.Column('detailed_category', sa.String(length=100), nullable=False),
    sa.Column('ui_label', sa.String(length=100), nullable=True),
    sa.Column('canonical_title', sa.String(length=150), nullable=True),
    sa.Column('canonical_group', sa.String(length=100), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('spend_type', sa.String(length=50), nullable=True),
    sa.Column('recurrence_likelihood', sa.String(length=20), nullable=True),
    sa.Column('velocity_risk', sa.String(length=20), nullable=True),
    sa.Column('chargeback_prone', sa.Boolean(), nullable=False),
    sa.Column('is_travel', sa.Boolean(), nullable=False),
    sa.Column('is_subscription_common', sa.Boolean(), nullable=False),
    sa.Column('is_luxury', sa.Boolean(), nullable=False),
    sa.Column('is_essential', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='merchants'
    )
    op.create_index(op.f('ix_merchants_merchant_category_codes_mcc'), 'merchant_category_codes', ['mcc'], unique=True, schema='merchants')
    op.create_table('merchant_master',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('merchant_slug', sa.String(length=100), nullable=False),
    sa.Column('clean_name', sa.String(length=100), nullable=False),
    sa.Column('default_mcc', sa.String(length=10), nullable=False),
    sa.Column('merchant_domain', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('is_subscription', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='merchants'
    )
    op.create_index('idx_merchants_domain', 'merchant_master', ['merchant_domain'], unique=False, schema='merchants')
    op.create_index('idx_merchants_mcc', 'merchant_master', ['default_mcc'], unique=False, schema='merchants')
    op.create_index(op.f('ix_merchants_merchant_master_merchant_slug'), 'merchant_master', ['merchant_slug'], unique=True, schema='merchants')
    op.create_table('fraud_alerts',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('customer_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('auth_provider_uid', sa.String(length=128), nullable=False),
    sa.Column('credit_account_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('card_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('card_last_four', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('message_thread_id', sa.String(length=128), nullable=False),
    sa.Column('suspicious_authorization_ids', sa.JSON(), nullable=False),
    sa.Column('suspicious_transactions', sa.JSON(), nullable=False),
    sa.Column('remediation_status', sa.String(length=32), nullable=False),
    sa.Column('triaged_at', sa.DateTime(), nullable=True),
    sa.Column('triage_summary', sa.String(length=512), nullable=True),
    sa.Column('selected_disputed_authorization_ids', sa.JSON(), nullable=False),
    sa.Column('selected_disputed_transaction_ids', sa.JSON(), nullable=False),
    sa.Column('provisional_credit_cents', sa.BigInteger(), nullable=False),
    sa.Column('replacement_card_id', utils.database.UniversalUUID(), nullable=True),
    sa.Column('triage_message_thread_id', sa.String(length=128), nullable=True),
    sa.Column('triage_message_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_thread_id'),
    schema='operations'
    )
    op.create_index('idx_fraud_alerts_customer_status', 'fraud_alerts', ['customer_id', 'status'], unique=False, schema='operations')
    op.create_index('idx_fraud_alerts_thread_id', 'fraud_alerts', ['message_thread_id'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_fraud_alerts_auth_provider_uid'), 'fraud_alerts', ['auth_provider_uid'], unique=False, schema='operations')
    op.create_table('fraud_case_actions',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('fraud_alert_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fraud_alert_id', 'idempotency_key', name='uq_fraud_case_actions_idempotency'),
    schema='operations'
    )
    op.create_index('idx_fraud_case_actions_alert', 'fraud_case_actions', ['fraud_alert_id'], unique=False, schema='operations')
    op.create_index('idx_fraud_case_actions_status', 'fraud_case_actions', ['status'], unique=False, schema='operations')
    op.create_index('idx_fraud_case_actions_type', 'fraud_case_actions', ['action_type'], unique=False, schema='operations')
    op.create_table('fraud_model_decisions',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('authorization_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('customer_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('credit_account_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('card_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('feature_snapshot', sa.JSON(), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('merchant_category_code', sa.String(length=4), nullable=True),
    sa.Column('transaction_channel', sa.String(length=32), nullable=True),
    sa.Column('merchant_country_code', sa.String(length=3), nullable=True),
    sa.Column('merchant_city', sa.String(length=100), nullable=True),
    sa.Column('merchant_region', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authorization_id', name='uq_fraud_model_decisions_authorization'),
    schema='operations'
    )
    op.create_index('idx_fraud_model_decisions_account_created', 'fraud_model_decisions', ['credit_account_id', 'created_at'], unique=False, schema='operations')
    op.create_index('idx_fraud_model_decisions_card_created', 'fraud_model_decisions', ['card_id', 'created_at'], unique=False, schema='operations')
    op.create_index('idx_fraud_model_decisions_customer_created', 'fraud_model_decisions', ['customer_id', 'created_at'], unique=False, schema='operations')
    op.create_table('retail_locations',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('hours', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('scenario_outcomes',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('scenario_id', sa.String(length=128), nullable=False),
    sa.Column('execution_id', sa.String(length=128), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('authorization_id', utils.database.UniversalUUID(), nullable=True),
    sa.Column('transaction_id', utils.database.UniversalUUID(), nullable=True),
    sa.Column('fraud_alert_id', utils.database.UniversalUUID(), nullable=True),
    sa.Column('customer_id', utils.database.UniversalUUID(), nullable=True),
    sa.Column('credit_account_id', utils.database.UniversalUUID(), nullable=True),
    sa.Column('card_id', utils.database.UniversalUUID(), nullable=True),
    sa.Column('card_token', sa.String(length=128), nullable=True),
    sa.Column('outcome_label', sa.String(length=64), nullable=False),
    sa.Column('expected_reason_codes', sa.JSON(), nullable=False),
    sa.Column('actual_reason_codes', sa.JSON(), nullable=False),
    sa.Column('expected_score_band', sa.String(length=64), nullable=True),
    sa.Column('actual_risk_score', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('synthetic_label', sa.Boolean(), nullable=False),
    sa.Column('operational_action', sa.String(length=64), nullable=True),
    sa.Column('operational_status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'execution_id', 'event_id', name='uq_scenario_outcomes_event'),
    schema='operations'
    )
    op.create_index('idx_scenario_outcomes_authorization', 'scenario_outcomes', ['authorization_id'], unique=False, schema='operations')
    op.create_index('idx_scenario_outcomes_customer_created', 'scenario_outcomes', ['customer_id', 'created_at'], unique=False, schema='operations')
    op.create_index('idx_scenario_outcomes_fraud_alert', 'scenario_outcomes', ['fraud_alert_id'], unique=False, schema='operations')
    op.create_index('idx_scenario_outcomes_scenario_execution', 'scenario_outcomes', ['scenario_id', 'execution_id'], unique=False, schema='operations')
    op.create_table('support_escalations',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('room_name', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('transcript', sa.JSON(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='operations'
    )
    op.create_table('synthetic_scheduled_events',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('schedule_id', sa.String(length=128), nullable=False),
    sa.Column('scenario_id', sa.String(length=128), nullable=True),
    sa.Column('execution_id', sa.String(length=128), nullable=True),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('parent_event_id', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('persona_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_synthetic_scheduled_events_idempotency'),
    schema='operations'
    )
    op.create_index('idx_synthetic_scheduled_events_scenario', 'synthetic_scheduled_events', ['scenario_id', 'execution_id'], unique=False, schema='operations')
    op.create_index('idx_synthetic_scheduled_events_schedule', 'synthetic_scheduled_events', ['schedule_id', 'scheduled_for'], unique=False, schema='operations')
    op.create_index('idx_synthetic_scheduled_events_status_time', 'synthetic_scheduled_events', ['status', 'scheduled_for'], unique=False, schema='operations')
    op.create_table('reset_epochs',
    sa.Column('scope_type', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.String(length=255), nullable=False),
    sa.Column('epoch', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('scope_type', 'scope_id'),
    schema='voice_support_sessions'
    )
    op.execute(
        sa.text(
            """
            INSERT INTO voice_support_sessions.reset_epochs
                (scope_type, scope_id, epoch)
            VALUES ('GLOBAL', '*', 0)
            ON CONFLICT (scope_type, scope_id) DO NOTHING
            """
        )
    )
    op.create_table('credit_accounts',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('customer_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credit_limit_cents', sa.BigInteger(), nullable=False),
    sa.Column('cleared_balance_cents', sa.BigInteger(), nullable=False),
    sa.Column('available_credit_cents', sa.BigInteger(), nullable=False),
    sa.Column('payment_due_date', sa.DateTime(), nullable=True),
    sa.Column('statement_close_date', sa.DateTime(), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('last_payment_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_code'], ['catalog.credit_products.product_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='cards'
    )
    op.create_index('idx_credit_accounts_customer_id', 'credit_accounts', ['customer_id'], unique=False, schema='cards')
    op.create_index('idx_credit_accounts_product_code', 'credit_accounts', ['product_code'], unique=False, schema='cards')
    op.create_table('user_addresses',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('user_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('address_type', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('street_line_1', sa.String(length=255), nullable=False),
    sa.Column('street_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('verified_by_doc_ai', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index('idx_user_addresses_user_id', 'user_addresses', ['user_id'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_user_addresses_city'), 'user_addresses', ['city'], unique=False, schema='identity')
    op.create_table('user_devices',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('user_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('device_token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index('idx_user_devices_user_id', 'user_devices', ['user_id'], unique=False, schema='identity')
    op.create_table('user_secure_messages',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=False),
    sa.Column('is_user_read', sa.Boolean(), nullable=True),
    sa.Column('is_agent_read', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index('idx_secure_msgs_thread_id', 'user_secure_messages', ['thread_id'], unique=False, schema='identity')
    op.create_index('idx_secure_msgs_user_id', 'user_secure_messages', ['user_id'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_user_secure_messages_message_id'), 'user_secure_messages', ['message_id'], unique=True, schema='identity')
    op.create_table('kyc_records',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('user_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('encrypted_pii', sa.LargeBinary(), nullable=False),
    sa.Column('wrapped_dek', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_iv', sa.LargeBinary(), nullable=False),
    sa.Column('auth_tag', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='kyc'
    )
    op.create_index('idx_kyc_records_user_id', 'kyc_records', ['user_id'], unique=False, schema='kyc')
    op.create_table('user_credit_profiles',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('user_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=False),
    sa.Column('credit_tier', sa.String(length=50), nullable=False),
    sa.Column('stated_annual_income_cents', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='kyc'
    )
    op.create_table('accounts',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('user_id', utils.database.UniversalUUID(), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('routing_number', sa.String(length=9), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credit_limit_cents', sa.BigInteger(), nullable=False),
    sa.Column('cleared_balance_cents', sa.BigInteger(), nullable=False),
    sa.Column('available_credit_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_code'], ['catalog.deposit_products.product_code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    schema='ledger'
    )
    op.create_index('idx_accounts_product_code', 'accounts', ['product_code'], unique=False, schema='ledger')
    op.create_index('idx_accounts_user_id', 'accounts', ['user_id'], unique=False, schema='ledger')
    op.create_table('transactions',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('user_id', utils.database.UniversalUUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('response_payload', sa.Text(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    schema='ledger'
    )
    op.create_index('idx_transactions_user_id', 'transactions', ['user_id'], unique=False, schema='ledger')
    op.create_table('merchant_stores',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('merchant_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.Column('raw_descriptor', sa.String(length=150), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('card_present_capable', sa.Boolean(), nullable=False),
    sa.Column('ecommerce_capable', sa.Boolean(), nullable=False),
    sa.Column('high_risk_flags', sa.String(length=255), nullable=True),
    sa.Column('is_international', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='merchants'
    )
    op.create_index('idx_stores_country', 'merchant_stores', ['country_code', 'is_international'], unique=False, schema='merchants')
    op.create_index('idx_stores_descriptor', 'merchant_stores', ['raw_descriptor'], unique=False, schema='merchants')
    op.create_index('idx_stores_risk', 'merchant_stores', ['risk_score'], unique=False, schema='merchants')
    op.create_index(op.f('ix_merchants_merchant_stores_merchant_id'), 'merchant_stores', ['merchant_id'], unique=False, schema='merchants')
    op.create_index(op.f('ix_merchants_merchant_stores_raw_descriptor'), 'merchant_stores', ['raw_descriptor'], unique=False, schema='merchants')
    op.create_table('applications',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('application_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('product_category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id'),
    schema='origination'
    )
    op.create_index('idx_applications_user_id', 'applications', ['user_id'], unique=False, schema='origination')
    op.create_table('issued_card',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('account_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('cardholder_name', sa.String(length=150), nullable=False),
    sa.Column('card_token', sa.String(length=255), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=False),
    sa.Column('encrypted_pin_block', sa.String(length=255), nullable=True),
    sa.Column('pin_fail_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('exp_month', sa.Integer(), nullable=False),
    sa.Column('exp_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_virtual', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cards.credit_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_token'),
    schema='cards'
    )
    op.create_index('idx_issued_card_token', 'issued_card', ['card_token'], unique=True, schema='cards')
    op.create_table('account_ledger',
    sa.Column('entry_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('transaction_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('account_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('entry_type', sa.String(length=10), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['ledger.accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger.transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entry_id'),
    schema='ledger'
    )
    op.create_index('idx_ledger_account_id', 'account_ledger', ['account_id'], unique=False, schema='ledger')
    op.create_index('idx_ledger_transaction_id', 'account_ledger', ['transaction_id'], unique=False, schema='ledger')
    op.create_table('application_artifacts',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('artifact_id', sa.String(length=128), nullable=False),
    sa.Column('application_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('customer_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('claimed_artifact_type', sa.String(length=100), nullable=True),
    sa.Column('actual_artifact_type', sa.String(length=100), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_payload', sa.Text(), nullable=True),
    sa.Column('audit_metadata', sa.Text(), nullable=True),
    sa.Column('verification_tier', sa.String(length=50), nullable=True),
    sa.Column('gcs_uri', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('version_id', sa.String(length=128), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['origination.applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id'),
    schema='origination'
    )
    op.create_index('idx_artifacts_application_id', 'application_artifacts', ['application_id'], unique=False, schema='origination')
    op.create_index('idx_artifacts_customer_id', 'application_artifacts', ['customer_id'], unique=False, schema='origination')
    op.create_table('credit_card_applications',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('application_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('requested_limit_cents', sa.BigInteger(), nullable=True),
    sa.Column('card_product_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['origination.applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id'),
    schema='origination'
    )
    op.create_table('deposit_applications',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('application_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('deposit_product_name', sa.String(length=100), nullable=True),
    sa.Column('initial_deposit_cents', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['origination.applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id'),
    schema='origination'
    )
    op.create_table('mortgage_applications',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('application_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('requested_loan_cents', sa.BigInteger(), nullable=True),
    sa.Column('property_address', sa.String(length=255), nullable=True),
    sa.Column('estimated_value_cents', sa.BigInteger(), nullable=True),
    sa.Column('loan_term_months', sa.Integer(), nullable=True),
    sa.Column('down_payment_cents', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['origination.applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id'),
    schema='origination'
    )
    op.create_table('transaction_authorization',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('card_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('account_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('transaction_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('transaction_currency', sa.String(length=3), nullable=False),
    sa.Column('billing_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('billing_currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decline_reason', sa.String(length=50), nullable=False),
    sa.Column('auth_code', sa.String(length=6), nullable=False),
    sa.Column('retrieval_reference_number', sa.String(length=12), nullable=False),
    sa.Column('card_network', sa.String(length=30), nullable=False),
    sa.Column('merchant_id', utils.database.UniversalUUID(), nullable=True),
    sa.Column('merchant_store_id', utils.database.UniversalUUID(), nullable=True),
    sa.Column('merchant_slug', sa.String(length=100), nullable=True),
    sa.Column('merchant_category_code', sa.String(length=4), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('transaction_channel', sa.String(length=32), nullable=True),
    sa.Column('entry_mode', sa.String(length=32), nullable=True),
    sa.Column('merchant_country_code', sa.String(length=3), nullable=True),
    sa.Column('merchant_city', sa.String(length=100), nullable=True),
    sa.Column('merchant_region', sa.String(length=100), nullable=True),
    sa.Column('merchant_postal_code', sa.String(length=20), nullable=True),
    sa.Column('merchant_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('merchant_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('ip_country_code', sa.String(length=3), nullable=True),
    sa.Column('shipping_country_code', sa.String(length=3), nullable=True),
    sa.Column('is_digital_goods', sa.Boolean(), nullable=False),
    sa.Column('fraud_risk_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cards.credit_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.issued_card.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_master.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_store_id'], ['merchants.merchant_stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='cards'
    )
    op.create_index('idx_auth_account_status', 'transaction_authorization', ['account_id', 'status'], unique=False, schema='cards')
    op.create_table('posted_transactions',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('account_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('authorization_id', utils.database.UniversalUUID(), nullable=True),
    sa.Column('auth_code', sa.String(length=6), nullable=True),
    sa.Column('retrieval_reference_number', sa.String(length=12), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cards.credit_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['authorization_id'], ['cards.transaction_authorization.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='cards'
    )
    op.create_index('idx_ledger_account', 'posted_transactions', ['account_id'], unique=False, schema='cards')
    op.create_index('idx_ledger_account_posted', 'posted_transactions', ['account_id', 'posted_at'], unique=False, schema='cards')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ledger_account_posted', table_name='posted_transactions', schema='cards')
    op.drop_index('idx_ledger_account', table_name='posted_transactions', schema='cards')
    op.drop_table('posted_transactions', schema='cards')
    op.drop_index('idx_auth_account_status', table_name='transaction_authorization', schema='cards')
    op.drop_table('transaction_authorization', schema='cards')
    op.drop_table('mortgage_applications', schema='origination')
    op.drop_table('deposit_applications', schema='origination')
    op.drop_table('credit_card_applications', schema='origination')
    op.drop_index('idx_artifacts_customer_id', table_name='application_artifacts', schema='origination')
    op.drop_index('idx_artifacts_application_id', table_name='application_artifacts', schema='origination')
    op.drop_table('application_artifacts', schema='origination')
    op.drop_index('idx_ledger_transaction_id', table_name='account_ledger', schema='ledger')
    op.drop_index('idx_ledger_account_id', table_name='account_ledger', schema='ledger')
    op.drop_table('account_ledger', schema='ledger')
    op.drop_index('idx_issued_card_token', table_name='issued_card', schema='cards')
    op.drop_table('issued_card', schema='cards')
    op.drop_index('idx_applications_user_id', table_name='applications', schema='origination')
    op.drop_table('applications', schema='origination')
    op.drop_index(op.f('ix_merchants_merchant_stores_raw_descriptor'), table_name='merchant_stores', schema='merchants')
    op.drop_index(op.f('ix_merchants_merchant_stores_merchant_id'), table_name='merchant_stores', schema='merchants')
    op.drop_index('idx_stores_risk', table_name='merchant_stores', schema='merchants')
    op.drop_index('idx_stores_descriptor', table_name='merchant_stores', schema='merchants')
    op.drop_index('idx_stores_country', table_name='merchant_stores', schema='merchants')
    op.drop_table('merchant_stores', schema='merchants')
    op.drop_index('idx_transactions_user_id', table_name='transactions', schema='ledger')
    op.drop_table('transactions', schema='ledger')
    op.drop_index('idx_accounts_user_id', table_name='accounts', schema='ledger')
    op.drop_index('idx_accounts_product_code', table_name='accounts', schema='ledger')
    op.drop_table('accounts', schema='ledger')
    op.drop_table('user_credit_profiles', schema='kyc')
    op.drop_index('idx_kyc_records_user_id', table_name='kyc_records', schema='kyc')
    op.drop_table('kyc_records', schema='kyc')
    op.drop_index(op.f('ix_identity_user_secure_messages_message_id'), table_name='user_secure_messages', schema='identity')
    op.drop_index('idx_secure_msgs_user_id', table_name='user_secure_messages', schema='identity')
    op.drop_index('idx_secure_msgs_thread_id', table_name='user_secure_messages', schema='identity')
    op.drop_table('user_secure_messages', schema='identity')
    op.drop_index('idx_user_devices_user_id', table_name='user_devices', schema='identity')
    op.drop_table('user_devices', schema='identity')
    op.drop_index(op.f('ix_identity_user_addresses_city'), table_name='user_addresses', schema='identity')
    op.drop_index('idx_user_addresses_user_id', table_name='user_addresses', schema='identity')
    op.drop_table('user_addresses', schema='identity')
    op.drop_index('idx_credit_accounts_product_code', table_name='credit_accounts', schema='cards')
    op.drop_index('idx_credit_accounts_customer_id', table_name='credit_accounts', schema='cards')
    op.drop_table('credit_accounts', schema='cards')
    op.drop_table('reset_epochs', schema='voice_support_sessions')
    op.drop_index('idx_synthetic_scheduled_events_status_time', table_name='synthetic_scheduled_events', schema='operations')
    op.drop_index('idx_synthetic_scheduled_events_schedule', table_name='synthetic_scheduled_events', schema='operations')
    op.drop_index('idx_synthetic_scheduled_events_scenario', table_name='synthetic_scheduled_events', schema='operations')
    op.drop_table('synthetic_scheduled_events', schema='operations')
    op.drop_table('support_escalations', schema='operations')
    op.drop_index('idx_scenario_outcomes_scenario_execution', table_name='scenario_outcomes', schema='operations')
    op.drop_index('idx_scenario_outcomes_fraud_alert', table_name='scenario_outcomes', schema='operations')
    op.drop_index('idx_scenario_outcomes_customer_created', table_name='scenario_outcomes', schema='operations')
    op.drop_index('idx_scenario_outcomes_authorization', table_name='scenario_outcomes', schema='operations')
    op.drop_table('scenario_outcomes', schema='operations')
    op.drop_table('retail_locations', schema='operations')
    op.drop_index('idx_fraud_model_decisions_customer_created', table_name='fraud_model_decisions', schema='operations')
    op.drop_index('idx_fraud_model_decisions_card_created', table_name='fraud_model_decisions', schema='operations')
    op.drop_index('idx_fraud_model_decisions_account_created', table_name='fraud_model_decisions', schema='operations')
    op.drop_table('fraud_model_decisions', schema='operations')
    op.drop_index('idx_fraud_case_actions_type', table_name='fraud_case_actions', schema='operations')
    op.drop_index('idx_fraud_case_actions_status', table_name='fraud_case_actions', schema='operations')
    op.drop_index('idx_fraud_case_actions_alert', table_name='fraud_case_actions', schema='operations')
    op.drop_table('fraud_case_actions', schema='operations')
    op.drop_index(op.f('ix_operations_fraud_alerts_auth_provider_uid'), table_name='fraud_alerts', schema='operations')
    op.drop_index('idx_fraud_alerts_thread_id', table_name='fraud_alerts', schema='operations')
    op.drop_index('idx_fraud_alerts_customer_status', table_name='fraud_alerts', schema='operations')
    op.drop_table('fraud_alerts', schema='operations')
    op.drop_index(op.f('ix_merchants_merchant_master_merchant_slug'), table_name='merchant_master', schema='merchants')
    op.drop_index('idx_merchants_mcc', table_name='merchant_master', schema='merchants')
    op.drop_index('idx_merchants_domain', table_name='merchant_master', schema='merchants')
    op.drop_table('merchant_master', schema='merchants')
    op.drop_index(op.f('ix_merchants_merchant_category_codes_mcc'), table_name='merchant_category_codes', schema='merchants')
    op.drop_table('merchant_category_codes', schema='merchants')
    op.drop_index(op.f('ix_identity_users_email'), table_name='users', schema='identity')
    op.drop_index(op.f('ix_identity_users_auth_provider_uid'), table_name='users', schema='identity')
    op.drop_table('users', schema='identity')
    op.drop_table('deposit_products', schema='catalog')
    op.drop_table('credit_products', schema='catalog')
    op.drop_index('idx_audit_outbox_event_type', table_name='audit_outbox', schema='audit')
    op.drop_index('idx_audit_outbox_created_at', table_name='audit_outbox', schema='audit')
    op.drop_table('audit_outbox', schema='audit')
    op.drop_index(op.f('ix_admin_system_settings_key'), table_name='system_settings', schema='admin')
    op.drop_table('system_settings', schema='admin')
    # ### end Alembic commands ###
