"""Add AuditOutbox table for compliance streaming

Revision ID: 47774a372ee4
Revises: 5646ebd24ecb
Create Date: 2026-06-26 20:37:05.758122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47774a372ee4'
down_revision: Union[str, Sequence[str], None] = '5646ebd24ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    schema='ledger'
    )
    op.create_index('idx_audit_outbox_event_id', 'audit_outbox', ['event_id'], unique=False, schema='ledger')
    op.create_index('idx_audit_outbox_status', 'audit_outbox', ['status'], unique=False, schema='ledger')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_outbox_status', table_name='audit_outbox', schema='ledger')
    op.drop_index('idx_audit_outbox_event_id', table_name='audit_outbox', schema='ledger')
    op.drop_table('audit_outbox', schema='ledger')
    # ### end Alembic commands ###
