"""Universal schema foundation and polymorphic origination

Revision ID: 5646ebd24ecb
Revises: 63766f3ca148
Create Date: 2026-06-26 20:28:00.858901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5646ebd24ecb'
down_revision: Union[str, Sequence[str], None] = '63766f3ca148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retail_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('hours', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auth_provider_uid', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_users_auth_provider_uid'), 'users', ['auth_provider_uid'], unique=True, schema='identity')
    op.create_index(op.f('ix_identity_users_email'), 'users', ['email'], unique=False, schema='identity')
    op.create_table('user_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index('idx_user_devices_user_id', 'user_devices', ['user_id'], unique=False, schema='identity')
    op.create_table('user_secure_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=False),
    sa.Column('is_user_read', sa.Boolean(), nullable=True),
    sa.Column('is_agent_read', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index('idx_secure_msgs_thread_id', 'user_secure_messages', ['thread_id'], unique=False, schema='identity')
    op.create_index('idx_secure_msgs_user_id', 'user_secure_messages', ['user_id'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_user_secure_messages_message_id'), 'user_secure_messages', ['message_id'], unique=True, schema='identity')
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credit_limit_cents', sa.BigInteger(), nullable=False),
    sa.Column('cleared_balance_cents', sa.BigInteger(), nullable=False),
    sa.Column('available_credit_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    schema='ledger'
    )
    op.create_index('idx_accounts_number', 'accounts', ['account_number'], unique=False, schema='ledger')
    op.create_index('idx_accounts_user_id', 'accounts', ['user_id'], unique=False, schema='ledger')
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id'),
    schema='ledger'
    )
    op.create_index('idx_applications_app_id', 'applications', ['application_id'], unique=False, schema='ledger')
    op.create_index('idx_applications_user_id', 'applications', ['user_id'], unique=False, schema='ledger')
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    schema='ledger'
    )
    op.create_index('idx_transactions_idempotency_key', 'transactions', ['idempotency_key'], unique=False, schema='ledger')
    op.create_index('idx_transactions_user_id', 'transactions', ['user_id'], unique=False, schema='ledger')
    op.create_table('account_ledger',
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('entry_type', sa.String(length=10), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['ledger.accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger.transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entry_id'),
    schema='ledger'
    )
    op.create_index('idx_ledger_account_id', 'account_ledger', ['account_id'], unique=False, schema='ledger')
    op.create_index('idx_ledger_transaction_id', 'account_ledger', ['transaction_id'], unique=False, schema='ledger')
    op.create_table('application_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.String(length=128), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('claimed_artifact_type', sa.String(length=100), nullable=True),
    sa.Column('gcs_uri', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('version_id', sa.String(length=128), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['ledger.applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['identity.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id'),
    schema='ledger'
    )
    op.create_index('idx_artifacts_application_id', 'application_artifacts', ['application_id'], unique=False, schema='ledger')
    op.create_index('idx_artifacts_customer_id', 'application_artifacts', ['customer_id'], unique=False, schema='ledger')
    op.create_table('credit_card_applications',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('requested_limit_cents', sa.BigInteger(), nullable=True),
    sa.Column('card_product_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['ledger.applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id'),
    schema='ledger'
    )
    op.create_table('deposit_applications',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('deposit_product_name', sa.String(length=100), nullable=True),
    sa.Column('initial_deposit_cents', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['ledger.applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id'),
    schema='ledger'
    )
    op.create_table('mortgage_applications',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('property_address', sa.String(length=255), nullable=True),
    sa.Column('estimated_value_cents', sa.BigInteger(), nullable=True),
    sa.Column('loan_term_months', sa.Integer(), nullable=True),
    sa.Column('down_payment_cents', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['ledger.applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id'),
    schema='ledger'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mortgage_applications', schema='ledger')
    op.drop_table('deposit_applications', schema='ledger')
    op.drop_table('credit_card_applications', schema='ledger')
    op.drop_index('idx_artifacts_customer_id', table_name='application_artifacts', schema='ledger')
    op.drop_index('idx_artifacts_application_id', table_name='application_artifacts', schema='ledger')
    op.drop_table('application_artifacts', schema='ledger')
    op.drop_index('idx_ledger_transaction_id', table_name='account_ledger', schema='ledger')
    op.drop_index('idx_ledger_account_id', table_name='account_ledger', schema='ledger')
    op.drop_table('account_ledger', schema='ledger')
    op.drop_index('idx_transactions_user_id', table_name='transactions', schema='ledger')
    op.drop_index('idx_transactions_idempotency_key', table_name='transactions', schema='ledger')
    op.drop_table('transactions', schema='ledger')
    op.drop_index('idx_applications_user_id', table_name='applications', schema='ledger')
    op.drop_index('idx_applications_app_id', table_name='applications', schema='ledger')
    op.drop_table('applications', schema='ledger')
    op.drop_index('idx_accounts_user_id', table_name='accounts', schema='ledger')
    op.drop_index('idx_accounts_number', table_name='accounts', schema='ledger')
    op.drop_table('accounts', schema='ledger')
    op.drop_index(op.f('ix_identity_user_secure_messages_message_id'), table_name='user_secure_messages', schema='identity')
    op.drop_index('idx_secure_msgs_user_id', table_name='user_secure_messages', schema='identity')
    op.drop_index('idx_secure_msgs_thread_id', table_name='user_secure_messages', schema='identity')
    op.drop_table('user_secure_messages', schema='identity')
    op.drop_index('idx_user_devices_user_id', table_name='user_devices', schema='identity')
    op.drop_table('user_devices', schema='identity')
    op.drop_index(op.f('ix_identity_users_email'), table_name='users', schema='identity')
    op.drop_index(op.f('ix_identity_users_auth_provider_uid'), table_name='users', schema='identity')
    op.drop_table('users', schema='identity')
    op.drop_table('retail_locations', schema='identity')
    # ### end Alembic commands ###
