"""Initial baseline schema

Revision ID: 63766f3ca148
Revises: 
Create Date: 2026-06-22 10:12:23.623891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63766f3ca148'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_account',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credit_limit_cents', sa.BigInteger(), nullable=False),
    sa.Column('cleared_balance_cents', sa.BigInteger(), nullable=False),
    sa.Column('available_credit_cents', sa.BigInteger(), nullable=False),
    sa.Column('payment_due_date', sa.DateTime(), nullable=True),
    sa.Column('statement_close_date', sa.DateTime(), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('last_payment_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_escalations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room_name', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('transcript', sa.JSON(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.create_table('issued_card',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('cardholder_name', sa.String(length=150), nullable=False),
    sa.Column('card_token', sa.String(length=255), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=False),
    sa.Column('encrypted_pin_block', sa.String(length=255), nullable=True),
    sa.Column('pin_fail_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('exp_month', sa.Integer(), nullable=False),
    sa.Column('exp_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_virtual', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['financial_account.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_token')
    )
    op.create_index('idx_issued_card_token', 'issued_card', ['card_token'], unique=True)
    op.create_table('transaction_authorization',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('transaction_currency', sa.String(length=3), nullable=False),
    sa.Column('billing_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('billing_currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decline_reason', sa.String(length=50), nullable=False),
    sa.Column('auth_code', sa.String(length=6), nullable=False),
    sa.Column('retrieval_reference_number', sa.String(length=12), nullable=False),
    sa.Column('card_network', sa.String(length=30), nullable=False),
    sa.Column('merchant_category_code', sa.String(length=4), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('fraud_risk_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['financial_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['card_id'], ['issued_card.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auth_account_status', 'transaction_authorization', ['account_id', 'status'], unique=False)
    op.create_table('account_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('authorization_id', sa.String(length=36), nullable=True),
    sa.Column('auth_code', sa.String(length=6), nullable=True),
    sa.Column('retrieval_reference_number', sa.String(length=12), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['financial_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['authorization_id'], ['transaction_authorization.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_account', 'account_ledger', ['account_id'], unique=False)
    op.create_index('idx_ledger_account_posted', 'account_ledger', ['account_id', 'posted_at'], unique=False)
    
    # Grant DML permissions to the runtime application user only if deploying against PostgreSQL
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # op.execute("GRANT USAGE ON SCHEMA public TO banking_runtime;")
        # op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO banking_runtime;")
        # op.execute("ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO banking_runtime;")
        
        import os
        from utils.gcp import get_project_id
        try:
            project_id = get_project_id()
        except Exception:
            project_id = os.getenv("PROJECT_ID")
        runtime_user = f"banking-service-sa@{project_id}.iam"
        migration_user = f"banking-migration-sa@{project_id}.iam"
        
        op.execute(f'GRANT USAGE ON SCHEMA public TO "{runtime_user}";')
        op.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "{runtime_user}";')
        op.execute(f'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "{runtime_user}";')
        
        op.execute(f'GRANT USAGE ON SCHEMA public TO "{migration_user}";')
        op.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "{migration_user}";')
        op.execute(f'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "{migration_user}";')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ledger_account_posted', table_name='account_ledger')
    op.drop_index('idx_ledger_account', table_name='account_ledger')
    op.drop_table('account_ledger')
    op.drop_index('idx_auth_account_status', table_name='transaction_authorization')
    op.drop_table('transaction_authorization')
    op.drop_index('idx_issued_card_token', table_name='issued_card')
    op.drop_table('issued_card')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_table('support_escalations')
    op.drop_table('financial_account')
    # ### end Alembic commands ###
