"""add fraud alerts

Revision ID: 7fb3570a7d09
Revises: 9e8f66b3e48e
Create Date: 2026-07-07 16:47:34.212249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import utils.database


# revision identifiers, used by Alembic.
revision: str = '7fb3570a7d09'
down_revision: Union[str, Sequence[str], None] = '9e8f66b3e48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_alerts',
    sa.Column('id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('customer_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('auth_provider_uid', sa.String(length=128), nullable=False),
    sa.Column('credit_account_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('card_id', utils.database.UniversalUUID(), nullable=False),
    sa.Column('card_last_four', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('message_thread_id', sa.String(length=128), nullable=False),
    sa.Column('suspicious_authorization_ids', sa.JSON(), nullable=False),
    sa.Column('suspicious_transactions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_thread_id'),
    schema='operations'
    )
    op.create_index('idx_fraud_alerts_customer_status', 'fraud_alerts', ['customer_id', 'status'], unique=False, schema='operations')
    op.create_index('idx_fraud_alerts_thread_id', 'fraud_alerts', ['message_thread_id'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_fraud_alerts_auth_provider_uid'), 'fraud_alerts', ['auth_provider_uid'], unique=False, schema='operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operations_fraud_alerts_auth_provider_uid'), table_name='fraud_alerts', schema='operations')
    op.drop_index('idx_fraud_alerts_thread_id', table_name='fraud_alerts', schema='operations')
    op.drop_index('idx_fraud_alerts_customer_status', table_name='fraud_alerts', schema='operations')
    op.drop_table('fraud_alerts', schema='operations')
    # ### end Alembic commands ###
