roles:
  - roles/serviceusage.serviceUsageAdmin
  - roles/resourcemanager.projectIamAdmin
  - roles/iam.serviceAccountAdmin
  - roles/iam.serviceAccountUser
  - roles/iam.roleAdmin
  - roles/compute.admin
  - roles/servicenetworking.networksAdmin
  - roles/run.admin
  - roles/cloudfunctions.admin
  - roles/cloudsql.admin
  - roles/redis.admin
  - roles/artifactregistry.admin
  - roles/storage.admin
  - roles/secretmanager.admin
  - roles/cloudkms.admin
  - roles/bigquery.admin
  - roles/datacatalog.admin
  - roles/datastream.admin
  - roles/pubsub.admin
  - roles/eventarc.admin
  - roles/cloudscheduler.admin
  - roles/cloudbuild.admin
  - roles/documentai.admin
  - roles/discoveryengine.admin
  - roles/firebase.admin
  - roles/identityplatform.admin
  - roles/certificatemanager.owner
  - roles/iap.admin
