roles:
  # Role to list datasets, tables, and create jobs
  - roles/bigquery.metadataViewer
  - roles/bigquery.jobUser

  # Roles to view Streams in console
  - roles/datastream.viewer

  # Roles to view Cloud Run in console
  - roles/run.viewer

  # Roles to view Pub/Sub topics and subscriptions in console
  - roles/pubsub.viewer

  # Roles to view Eventarc triggers in console
  - roles/eventarc.viewer

  # Roles to view Cloud Scheduler jobs in console
  - roles/cloudscheduler.viewer

  # Roles to view Artifact Registry in console
  - roles/artifactregistry.viewer

  # Roles to view Compute Engine in console
  - roles/compute.viewer

  # Roles to view Redis in console
  - roles/redis.viewer

  # Roles to view KMS in console
  - roles/cloudkms.viewer

  # Roles to view Data Catalog Policy Tag Taxonomies in console
  - roles/datacatalog.viewer
