# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - name: "ghcr.io/astral-sh/uv:python3.13-alpine"
    dir: "adk-agent"
    id: "export-uv-requirements"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        # Run the uv export command
        # The output is piped to a file in the workspace
        echo "Running uv export to generate requirements file..."
        uv export \
          --no-hashes \
          --no-header \
          --no-dev \
          --no-emit-project \
          --no-annotate \
          > ./back-office-agent/requirements.txt

        echo "Generated requirements file contents:"
        cat ./back-office-agent/requirements.txt
        echo "Finished exporting requirements."

  - name: 'python:3.13-slim'
    dir: 'adk-agent/back-office-agent'
    id: 'Install ADK and Deploy Back Office Agent'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        # Install the required ADK library globally within the container
        echo "Installing google-adk..."
        pip install google-adk

        # Execute the deployment command
        echo "Starting ADK deployment..."
        adk deploy agent_engine \
          --project=${PROJECT_ID} \
          --region=${_REGION} \
          --display_name="${_DISPLAY_NAME}" \
          --trace_to_cloud \
          --env_file="./agent/.env" \
          --agent_engine_id="${_AGENT_ENGINE_ID}" \
          ./agent

    timeout: '1800s' # 30 minutes

options:
  pool:
    name: 'projects/${PROJECT_ID}/locations/${_REGION}/workerPools/build-pool'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'us-central1'
  _DISPLAY_NAME: 'back-office-agent'
  _TRIGGER_CLEANUP: "false"
  _AGENT_ENGINE_ID: "7620218662615515136"
