name: Lint Banking Service

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

on:
  push:
    branches: [ main ]
    paths:
      - 'banking-service/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'banking-service/**'

jobs:
  lint:
    name: Run Ruff Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
        with:
          src: './banking-service'
