name: Lint Blocking Function

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

on:
  push:
    branches: [ main ]
    paths:
      - 'blocking-function/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'blocking-function/**'

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: npm install
        working-directory: blocking-function

      - name: Run ESLint
        run: npm run lint
        working-directory: blocking-function
